version: '2.4'

# Âncoras para configurações comuns
x-logging: &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "10m"

x-healthcheck: &default-healthcheck
  test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
  interval: 30s
  retries: 3
  start_period: 10s
  timeout: 10s

x-restart: &default-restart
  restart: always

x-mongo-volumes: &default-mongo-volumes
  - ./mnt/mongodb:/data/db
  - ./mnt/mongodb_configData:/data/configdb
  - ./mnt/mongodb_init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

services:
  # Serviço MongoDB
  database-mongodb:
    image: mongo:7
    container_name: mongodb
    networks:
      - hadoop_network
    volumes:
      <<: *default-mongo-volumes
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS_ADMIN}
    ports:
      - "27017:27017"
    <<: *default-restart
    healthcheck:
      <<: *default-healthcheck

  # Serviço MongoDB Exporter para Prometheus
  mongo-exporter:
    container_name: mongo-exporter
    image: bitnami/mongodb-exporter:latest
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER_ADMIN}:${MONGO_PASS_ADMIN}@mongodb:27017
    networks:
      - hadoop_network
    logging:
      <<: *default-logging

volumes:
  mongodb_data:
    driver: local
  mongodb_configdb_data:
    driver: local

networks:
  hadoop_network:
    external: true
    driver: bridge
