version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "10m"

x-healthcheck: &default-healthcheck
  test: ["CMD", "nc", "-z", "localhost", "port"]
  timeout: 45s
  interval: 10s
  retries: 10

x-environment: &default-environment
  CLUSTER_NAME: hadoop_cluster

x-restart: &default-restart
  restart: always

services:
  infra-namenode:
    image: iamgacarvalho/hadoop-namenode-data-in-compass:0.0.3
    container_name: namenode
    networks:
      hadoop_network:
        aliases:
          - namenode
    logging: *default-logging
    ports:
      - "32763:9870"
    volumes:
      - ../../mnt/hadoop/namenode:/hadoop/dfs/name
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "nc", "-z", "localhost", "9870"]
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '5.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    environment:
      CLUSTER_NAME: hadoop_cluster
      SPARK_DRIVER_CORES: 4
      SPARK_EXECUTOR_CORES: 4
      SPARK_DRIVER_MEMORY: 4G
      SPARK_EXECUTOR_MEMORY: 4G

  infra-datanode:
    image: iamgacarvalho/hadoop-datanode-data-in-compass:0.0.3
    container_name: datanode
    networks:
      hadoop_network:
        aliases:
          - datanode
    logging: *default-logging
    ports:
      - "9854-9864:9864"
    volumes:
      - ../../mnt/hadoop/datanode:/hadoop/dfs/data
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 8G
          cpus: '5.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    environment:
      CLUSTER_NAME: hadoop_cluster
      SERVICE_PRECONDITION: infra-namenode:9870
      DATANODE_PORT: 9864
      SPARK_DRIVER_CORES: 4
      SPARK_EXECUTOR_CORES: 4
      SPARK_DRIVER_MEMORY: 4G
      SPARK_EXECUTOR_MEMORY: 4G

  # Serviço do infra-history-server
  infra-history-server:
    image: iamgacarvalho/hadoop-historyserver-data-in-compass:0.0.3
    container_name: history-server
    networks:
      hadoop_network:
        aliases:
          - history-server
    logging: *default-logging
    ports:
      - "8188:8188"
    environment:
      SERVICE_PRECONDITION: namenode:9870
      DATANODE_PORT: 8188
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 3G
          cpus: '5.0'
        reservations:
          memory: 1G
          cpus: '2.0'
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD", "nc", "-z", "localhost", "8188" ]

  infra-resourcemanager:
    image: iamgacarvalho/hadoop-resourcemanager-data-in-compass:0.0.3
    container_name: resourcemanager
    networks:
      hadoop_network:
        aliases:
          - resourcemanager
    logging: *default-logging
    ports:
      - "8088:8088"
    environment:
      SERVICE_PRECONDITION: infra-namenode:9870
      DATANODE_PORT: 8188
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 3G
          cpus: '5.0'
        reservations:
          memory: 1G
          cpus: '2.0'
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD", "nc", "-z", "localhost", "8088" ]

  infra-nodemanager:
    image: iamgacarvalho/hadoop-nodemanager-data-in-compass:0.0.3
    container_name: nodemanager
    networks:
      hadoop_network:
        aliases:
          - nodemanager
    logging: *default-logging
    ports:
      - "8032-8042:8042"
    environment:
      SERVICE_PRECONDITION: infra-namenode:9870
      DATANODE_PORT: 8188
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 3G
          cpus: '10.0'
        reservations:
          memory: 1G
          cpus: '2.0'
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD", "nc", "-z", "localhost", "8042" ]

volumes:
  infra-namenode:
  infra-datanode:

networks:
  hadoop_network:
    external: true
    driver: overlay
